networks:
  external_aggregator_network:
    external: true
  external_traffic_network:
    external: true
  sogno_network:
    driver: bridge
services:
  api:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    container_name: ServiceAPI
    networks:
    - sogno_network
    ports:
    - 7000:7000
  connector_2:
    build:
      context: ./connector
      dockerfile: ./Dockerfile
    container_name: connector_2
    depends_on:
    - coordinator
    environment:
    - CONNECTOR_ID=aggregator_2
    - AGGREGATOR_URL=http://host.docker.internal:9002/availability/
    - REQUEST_TOPIC=availability/request/aggregator_2
    - RESPONSE_TOPIC=availability/response/aggregator_2
    - PYTHONUNBUFFERED=1
    networks:
    - sogno_network
    - external_aggregator_network
  connector_4:
    build:
      context: ./connector
      dockerfile: ./Dockerfile
    container_name: connector_4
    depends_on:
    - coordinator
    environment:
    - CONNECTOR_ID=aggregator_4
    - AGGREGATOR_URL=http://host.docker.internal:9004/availability/
    - REQUEST_TOPIC=availability/request/aggregator_4
    - RESPONSE_TOPIC=availability/response/aggregator_4
    - PYTHONUNBUFFERED=1
    networks:
    - sogno_network
    - external_aggregator_network
  connector_5:
    build:
      context: ./connector
      dockerfile: ./Dockerfile
    container_name: connector_5
    depends_on:
    - coordinator
    environment:
    - CONNECTOR_ID=aggregator_5
    - AGGREGATOR_URL=http://host.docker.internal:9005/availability/
    - REQUEST_TOPIC=availability/request/aggregator_5
    - RESPONSE_TOPIC=availability/response/aggregator_5
    - PYTHONUNBUFFERED=1
    networks:
    - sogno_network
    - external_aggregator_network
  connector_abc:
    build:
      context: ./connector
      dockerfile: ./Dockerfile
    container_name: connector_abc
    depends_on:
    - coordinator
    environment:
    - CONNECTOR_ID=aggregator_abc
    - AGGREGATOR_URL=http://host.docker.internal:9001/availability/
    - REQUEST_TOPIC=availability/request/aggregator_abc
    - RESPONSE_TOPIC=availability/response/aggregator_abc
    - PYTHONUNBUFFERED=1
    networks:
    - sogno_network
    - external_aggregator_network
  connector_c:
    build:
      context: ./connector
      dockerfile: ./Dockerfile
    container_name: connector_c
    depends_on:
    - coordinator
    environment:
    - CONNECTOR_ID=aggregator_c
    - AGGREGATOR_URL=http://host.docker.internal:9003/availability/
    - REQUEST_TOPIC=availability/request/aggregator_c
    - RESPONSE_TOPIC=availability/response/aggregator_c
    - PYTHONUNBUFFERED=1
    networks:
    - sogno_network
    - external_aggregator_network
  coordinator:
    build:
      context: ./coordinator
      dockerfile: ./Dockerfile
    container_name: coordinator
    environment:
    - TRAFFIC_URL=http://host.docker.internal:8000/trafficforecast/
    - PYTHONUNBUFFERED=1
    networks:
    - sogno_network
    - external_traffic_network
  gatewaymqtt:
    container_name: broker
    expose:
    - '1883'
    image: toke/mosquitto
    networks:
    - sogno_network
    ports:
    - 1883:1883
    restart: unless-stopped
  routingalgorithm:
    build:
      context: ./optimizer
      dockerfile: ./Dockerfile
    container_name: Optimizer
    environment:
    - PYTHONUNBUFFERED=1
    networks:
    - sogno_network
version: '3'
