networks:
  external_aggregator_network:
    external: true
  external_traffic_network:
    external: true
  sogno_network:
    driver: bridge
services:
  api:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    container_name: ServiceAPI
    networks:
    - sogno_network
    ports:
    - 7000:7000
  connector_1:
    build:
      context: ./connector
      dockerfile: ./Dockerfile
    container_name: connector_1
    depends_on:
    - coordinator
    environment:
    - CONNECTOR_ID=aggregator_1
    - AGGREGATOR_AVAILABILITY_URL=http://host.docker.internal:9001/availability/
    - AGGREGATOR_SCHEDULE_URL=http://host.docker.internal:9001/schedule/
    - REQUEST_TOPIC=availability/request/aggregator_1
    - RESPONSE_TOPIC=availability/response/aggregator_1
    - PYTHONUNBUFFERED=1
    networks:
    - sogno_network
    - external_aggregator_network
  coordinator:
    build:
      context: ./coordinator
      dockerfile: ./Dockerfile
    container_name: coordinator
    environment:
    - TRAFFIC_URL=http://host.docker.internal:8000/trafficforecast/
    - PYTHONUNBUFFERED=1
    networks:
    - sogno_network
    - external_traffic_network
  gatewaymqtt:
    container_name: broker
    expose:
    - '1883'
    image: toke/mosquitto
    networks:
    - sogno_network
    ports:
    - 1883:1883
    restart: unless-stopped
  routingalgorithm:
    build:
      context: ./optimizer
      dockerfile: ./Dockerfile
    container_name: Optimizer
    environment:
    - PYTHONUNBUFFERED=1
    networks:
    - sogno_network
version: '3'
