networks:
  external_aggregator_network:
    external: true
  external_traffic_network:
    external: true
  sogno_network:
    driver: bridge
services:
  api:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    container_name: ServiceAPI
    networks:
    - sogno_network
    ports:
    - 7000:7000
  connector1:
    build:
      context: ./connector
      dockerfile: ./Dockerfile
    container_name: connector1
    depends_on:
    - coordinator
    environment:
    - CONNECTOR_ID=aggregator1
    - AGGREGATOR_URL=http://host.docker.internal:9001/availability/
    - REQUEST_TOPIC=availability/request/aggregator1
    - RESPONSE_TOPIC=availability/response/aggregator1
    - PYTHONUNBUFFERED=1
    networks:
    - sogno_network
    - external_aggregator_network
  connector2:
    build:
      context: ./connector
      dockerfile: ./Dockerfile
    container_name: connector2
    depends_on:
    - coordinator
    environment:
    - CONNECTOR_ID=aggregator2
    - AGGREGATOR_URL=http://host.docker.internal:9002/availability/
    - REQUEST_TOPIC=availability/request/aggregator2
    - RESPONSE_TOPIC=availability/response/aggregator2
    - PYTHONUNBUFFERED=1
    networks:
    - sogno_network
    - external_aggregator_network
  connector3:
    build:
      context: ./connector
      dockerfile: ./Dockerfile
    container_name: connector3
    depends_on:
    - coordinator
    environment:
    - CONNECTOR_ID=aggregator3
    - AGGREGATOR_URL=http://host.docker.internal:9003/availability/
    - REQUEST_TOPIC=availability/request/aggregator3
    - RESPONSE_TOPIC=availability/response/aggregator3
    - PYTHONUNBUFFERED=1
    networks:
    - sogno_network
    - external_aggregator_network
  connector4:
    build:
      context: ./connector
      dockerfile: ./Dockerfile
    container_name: connector4
    depends_on:
    - coordinator
    environment:
    - CONNECTOR_ID=aggregator4
    - AGGREGATOR_URL=http://host.docker.internal:9004/availability/
    - REQUEST_TOPIC=availability/request/aggregator4
    - RESPONSE_TOPIC=availability/response/aggregator4
    - PYTHONUNBUFFERED=1
    networks:
    - sogno_network
    - external_aggregator_network
  connector5:
    build:
      context: ./connector
      dockerfile: ./Dockerfile
    container_name: connector5
    depends_on:
    - coordinator
    environment:
    - CONNECTOR_ID=aggregator5
    - AGGREGATOR_URL=http://host.docker.internal:9005/availability/
    - REQUEST_TOPIC=availability/request/aggregator5
    - RESPONSE_TOPIC=availability/response/aggregator5
    - PYTHONUNBUFFERED=1
    networks:
    - sogno_network
    - external_aggregator_network
  coordinator:
    build:
      context: ./coordinator
      dockerfile: ./Dockerfile
    container_name: coordinator
    environment:
    - TRAFFIC_URL=http://host.docker.internal:8000/trafficforecast/
    - PYTHONUNBUFFERED=1
    networks:
    - sogno_network
    - external_traffic_network
  gatewaymqtt:
    container_name: broker
    expose:
    - '1883'
    image: toke/mosquitto
    networks:
    - sogno_network
    ports:
    - 1883:1883
    restart: unless-stopped
  routingalgorithm:
    build:
      context: ./optimizer
      dockerfile: ./Dockerfile
    container_name: Optimizer
    environment:
    - PYTHONUNBUFFERED=1
    networks:
    - sogno_network
version: '3'
