# Configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: evrich-config
data:
  MQTT_URL: evrich-mqtt-broker-service
  MQTT_PORT: "1883"
  ROUTING_REQUEST_TOPIC: routing/request/emo
  ROUTING_RESPONSE_TOPIC: routing/response/emo
  TRAFFIC_URL: http://evrich-traffic-service:8000/trafficforecast/
  AGGREGATOR_URL_1: http://evrich-aggregator-1-service:9001/availability/
  AGGREGATOR_URL_2: http://evrich-aggregator-2-service:9002/availability/
  AGGREGATOR_URL_3: http://evrich-aggregator-3-service:9003/availability/
  CONNECTOR_ID_1: aggregator1
  CONNECTOR_ID_2: aggregator2
  CONNECTOR_ID_3: aggregator3
  AGGREGATOR_REQUEST_TOPIC_1: availability/request/aggregator1
  AGGREGATOR_REQUEST_TOPIC_2: availability/request/aggregator2
  AGGREGATOR_REQUEST_TOPIC_3: availability/request/aggregator3
  AGGREGATOR_RESPONSE_TOPIC_1: availability/response/aggregator1
  AGGREGATOR_RESPONSE_TOPIC_2: availability/response/aggregator2
  AGGREGATOR_RESPONSE_TOPIC_3: availability/response/aggregator3
---
# MQTT
apiVersion: apps/v1
kind: Deployment
metadata:
  name: evrich-mqtt-broker
  namespace: sogno-dev
spec:
  selector:
    matchLabels:
      app: evrich-mqtt-broker
  template:
    metadata:
      labels:
        app: evrich-mqtt-broker
    spec:
      containers:
        - name: evrich-mqtt-broker
          image: toke/mosquitto
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          envFrom:
            - configMapRef:
                name: evrich-config
          ports:
            - containerPort: 1883
---
apiVersion: v1
kind: Service
metadata:
  name: evrich-mqtt-broker-service
  namespace: sogno-dev
spec:
  selector:
    app: evrich-mqtt-broker
  ports:
    - protocol: TCP
      port: 1883
      targetPort: 1883
---
#API
apiVersion: apps/v1
kind: Deployment
metadata:
  name: evrich-api
  namespace: sogno-dev
  labels:
    app: evrich-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: evrich-api
  template:
    metadata:
      labels:
        app: evrich-api
    spec:
      imagePullSecrets:
        - name: gitlab-evrich-token
      containers:
        - name: evrich-routing
          image: registry.git.rwth-aachen.de/acs/public/automation/evrich/api
          resources:
            limits:
              memory: 1G
              cpu: 1.0
          ports:
            - containerPort: 7000
          imagePullPolicy: Always
          env:
            - name: MQTT_URL
              valueFrom:
                configMapKeyRef:
                  name: evrich-config
                  key: MQTT_URL
            - name: MQTT_PORT
              valueFrom:
                configMapKeyRef:
                  name: evrich-config
                  key: MQTT_PORT
---
apiVersion: v1
kind: Service
metadata:
  name: evrich-api
  namespace: sogno-dev
  labels:
    app: evrich-api
spec:
  type: NodePort
  selector:
    app: evrich-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7000

---
# Coordinator
apiVersion: apps/v1
kind: Deployment
metadata:
  name: evrich-coordinator
  namespace: sogno-dev
  labels:
    app: evrich-coordinator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: evrich-coordinator
  template:
    metadata:
      labels:
        app: evrich-coordinator
    spec:
      imagePullSecrets:
        - name: gitlab-evrich-token
      containers:
        - name: evrich-coordinator
          image: registry.git.rwth-aachen.de/acs/public/automation/evrich/coordinator
          resources:
            limits:
              memory: 1G
              cpu: 1.0
          imagePullPolicy: Always
          # TODO: this wont work routing does not knwo what to to with these
          envFrom:
            - configMapRef:
                name: evrich-config
---
# SmartRouting
apiVersion: apps/v1
kind: Deployment
metadata:
  name: evrich-routing
  namespace: sogno-dev
  labels:
    app: evrich-routing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: evrich-routing
  template:
    metadata:
      labels:
        app: evrich-routing
    spec:
      imagePullSecrets:
        - name: gitlab-evrich-token
      containers:
        - name: evrich-routing
          image: registry.git.rwth-aachen.de/acs/public/automation/evrich/routing
          resources:
            limits:
              memory: 1G
              cpu: 1.0
          imagePullPolicy: Always
          # TODO: this wont work routing does not knwo what to to with these
          envFrom:
            - configMapRef:
                name: evrich-config
---
# Conectors
## 1
apiVersion: apps/v1
kind: Deployment
metadata:
  name: evrich-connector-1
  namespace: sogno-dev
  labels:
    app: evrich-connector-1
spec:
  selector:
    matchLabels:
      app: evrich-connector-1
  template:
    metadata:
      labels:
        app: evrich-connector-1
    spec:
      imagePullSecrets:
        - name: gitlab-evrich-token
      containers:
        - name: evrich-connector-1
          image: registry.git.rwth-aachen.de/acs/public/automation/evrich/connector
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: CONNECTOR_ID
              valueFrom:
                configMapKeyRef:
                  name: evrich-config
                  key: CONNECTOR_ID_1
            - name: AGGREGATOR_URL
              valueFrom:
                configMapKeyRef:
                  name: evrich-config
                  key: AGGREGATOR_URL_1
            - name: MQTT_URL
              valueFrom:
                configMapKeyRef:
                  name: evrich-config
                  key: MQTT_URL
            - name: MQTT_PORT
              valueFrom:
                configMapKeyRef:
                  name: evrich-config
                  key: MQTT_PORT
            - name: REQUEST_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: evrich-config
                  key: AGGREGATOR_REQUEST_TOPIC_1
            - name: RESPONSE_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: evrich-config
                  key: AGGREGATOR_RESPONSE_TOPIC_1

---
##2
apiVersion: apps/v1
kind: Deployment
metadata:
  name: evrich-connector-2
  namespace: sogno-dev
  labels:
    app: evrich-connector-2
spec:
  selector:
    matchLabels:
      app: evrich-connector-2
  template:
    metadata:
      labels:
        app: evrich-connector-2
    spec:
      imagePullSecrets:
        - name: gitlab-evrich-token
      containers:
        - name: evrich-connector-2
          image: registry.git.rwth-aachen.de/acs/public/automation/evrich/connector
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: CONNECTOR_ID
              valueFrom:
                configMapKeyRef:
                  name: evrich-config
                  key: CONNECTOR_ID_2
            - name: AGGREGATOR_URL
              valueFrom:
                configMapKeyRef:
                  name: evrich-config
                  key: AGGREGATOR_URL_2
            - name: MQTT_URL
              valueFrom:
                configMapKeyRef:
                  name: evrich-config
                  key: MQTT_URL
            - name: MQTT_PORT
              valueFrom:
                configMapKeyRef:
                  name: evrich-config
                  key: MQTT_PORT
            - name: REQUEST_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: evrich-config
                  key: AGGREGATOR_REQUEST_TOPIC_2
            - name: RESPONSE_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: evrich-config
                  key: AGGREGATOR_RESPONSE_TOPIC_2
---
##3
apiVersion: apps/v1
kind: Deployment
metadata:
  name: evrich-connector-3
  namespace: sogno-dev
  labels:
    app: evrich-connector-3
spec:
  selector:
    matchLabels:
      app: evrich-connector-3
  template:
    metadata:
      labels:
        app: evrich-connector-3
    spec:
      imagePullSecrets:
        - name: gitlab-evrich-token
      containers:
        - name: evrich-connector-3
          image: registry.git.rwth-aachen.de/acs/public/automation/evrich/connector
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: CONNECTOR_ID
              valueFrom:
                configMapKeyRef:
                  name: evrich-config
                  key: CONNECTOR_ID_3
            - name: AGGREGATOR_URL
              valueFrom:
                configMapKeyRef:
                  name: evrich-config
                  key: AGGREGATOR_URL_3
            - name: MQTT_URL
              valueFrom:
                configMapKeyRef:
                  name: evrich-config
                  key: MQTT_URL
            - name: MQTT_PORT
              valueFrom:
                configMapKeyRef:
                  name: evrich-config
                  key: MQTT_PORT
            - name: REQUEST_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: evrich-config
                  key: AGGREGATOR_REQUEST_TOPIC_3
            - name: RESPONSE_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: evrich-config
                  key: AGGREGATOR_RESPONSE_TOPIC_3
# apiVersion: v1
# kind: Service
# metadata:
#   name: evrich-routing-service
#   namespace: sogno-dev
# spec:
#   selector:
#     app: evrich-routing
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 80

# ---

# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   annotations:
#     cert-manager.io/cluster-issuer: letsencrypt-prod
#     eonerc.rwth-aachen.de/description: Datafev Documentation
#     kubernetes.io/ingress.class: nginx
#   name: datafev-doc
#   namespace: fein
# spec:
#   rules:
#   - host: datafev.fein-aachen.org
#     http:
#       paths:
#       - backend:
#           service:
#             name: datafev-doc-service
#             port:
#               number: 80
#         path: /
#         pathType: ImplementationSpecific
#   tls:
#     - hosts:
#       - datafev.fein-aachen.org
#       secretName: letsencrypt-prod-datafev
