networks:
  aggregator_network:
    driver: bridge
  external_network:
    driver: bridge
  traffic_network:
    driver: bridge
services:
  aggregator_1:
    build:
      context: ./aggregator
      dockerfile: ./Dockerfile
    container_name: aggregator_1
    depends_on:
    - datafev
    environment:
    - CLUSTER_ID=1
    - IP_ADDRESS=0.0.0.0
    - PORT_NUMBER=9001
    - PYTHONUNBUFFERED=1
    - DATAFEV_CHARGER_SELECTION_URL=http://host.docker.internal:9004/charger_selection/
    - DATAFEV_RESERVATION_URL=http://host.docker.internal:9004/reservation/
    networks:
    - aggregator_network
    ports:
    - 9001:9001
  aggregator_2:
    build:
      context: ./aggregator
      dockerfile: ./Dockerfile
    container_name: aggregator_2
    depends_on:
    - datafev
    environment:
    - CLUSTER_ID=2
    - IP_ADDRESS=0.0.0.0
    - PORT_NUMBER=9002
    - PYTHONUNBUFFERED=1
    - DATAFEV_CHARGER_SELECTION_URL=http://host.docker.internal:9004/charger_selection/
    - DATAFEV_RESERVATION_URL=http://host.docker.internal:9004/reservation/
    networks:
    - aggregator_network
    ports:
    - 9002:9002
  datafev:
    build:
      context: ./datafev
      dockerfile: ./Dockerfile
    container_name: datafev
    environment:
    - PYTHONUNBUFFERED=1
    - MYSQL_HOST=mysql
    - MYSQL_PORT=3306
    - MYSQL_USER=root
    - MYSQL_PASSWORD=root
    - MYSQL_DB=mydatabase
    networks:
    - external_network
    ports:
    - 9004:9004
  event_manager:
    build:
      context: ./event_manager
      dockerfile: ./Dockerfile
    container_name: event_manager
    depends_on:
    - datafev
    environment:
    - SERVICE_API_URL=http://host.docker.internal:7000/routing/post_request_type1/
    - DATAFEV_INIT_URL=http://host.docker.internal:9004/datafev_init/
    - DATAFEV_GET_REQUEST_COUNTER_URL=http://host.docker.internal:9004/get_request_counter/
    - DATAFEV_SYNCHRONIZE_URL=http://host.docker.internal:9004/synchronize/
    - PYTHONUNBUFFERED=1
    networks:
    - external_network
  trafficapi:
    build:
      context: ./traffic
      dockerfile: ./Dockerfile
    container_name: TrafficAPI
    environment:
    - PYTHONUNBUFFERED=1
    networks:
    - traffic_network
    ports:
    - 8000:8000
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mydatabase
    ports:
      - 3306:3306
    networks:
      - external_network  
version: '3'

