networks:
  aggregator_network:
    driver: bridge
  traffic_network:
    driver: bridge
services:
  aggregator_2:
    build:
      context: ./aggregator
      dockerfile: ./Dockerfile
    container_name: aggregator_2
    environment:
    - CLUSTER_ID=2
    - IP_ADDRESS=0.0.0.0
    - PORT_NUMBER=9002
    - PYTHONUNBUFFERED=1
    networks:
    - aggregator_network
    ports:
    - 9002:9002
  aggregator_4:
    build:
      context: ./aggregator
      dockerfile: ./Dockerfile
    container_name: aggregator_4
    environment:
    - CLUSTER_ID=4
    - IP_ADDRESS=0.0.0.0
    - PORT_NUMBER=9004
    - PYTHONUNBUFFERED=1
    networks:
    - aggregator_network
    ports:
    - 9004:9004
  aggregator_5:
    build:
      context: ./aggregator
      dockerfile: ./Dockerfile
    container_name: aggregator_5
    environment:
    - CLUSTER_ID=5
    - IP_ADDRESS=0.0.0.0
    - PORT_NUMBER=9005
    - PYTHONUNBUFFERED=1
    networks:
    - aggregator_network
    ports:
    - 9005:9005
  aggregator_abc:
    build:
      context: ./aggregator
      dockerfile: ./Dockerfile
    container_name: aggregator_abc
    environment:
    - CLUSTER_ID=abc
    - IP_ADDRESS=0.0.0.0
    - PORT_NUMBER=9001
    - PYTHONUNBUFFERED=1
    networks:
    - aggregator_network
    ports:
    - 9001:9001
  aggregator_c:
    build:
      context: ./aggregator
      dockerfile: ./Dockerfile
    container_name: aggregator_c
    environment:
    - CLUSTER_ID=c
    - IP_ADDRESS=0.0.0.0
    - PORT_NUMBER=9003
    - PYTHONUNBUFFERED=1
    networks:
    - aggregator_network
    ports:
    - 9003:9003
  trafficapi:
    build:
      context: ./traffic
      dockerfile: ./Dockerfile
    container_name: TrafficAPI
    environment:
    - PYTHONUNBUFFERED=1
    networks:
    - traffic_network
    ports:
    - 8000:8000
version: '3'
